### ISSUE TITLE
Stuck at 2nd bullet point....

### ISSUE THREAD

**Issue by arretx** [abhn/Wall-E#2]
"Fork this repository, rename the fork as your-username.github.io. Your blog should immediately be live on https://your-username.github.io"

Does this work with Organization names, as it doesn't seem to.

I got it working on my local machine, but on GitHub, no go.

**Comment by abhn** [comment]
Hey, thanks for dropping by.

I believe it does, I've hosted the Wall-E demo repo that way here: https://github.com/wall-e-jekyll/wall-e-jekyll.github.io

Let me know if anything else.
