### ISSUE TITLE
HomePage and Archieve not updating

### ISSUE THREAD

**Issue by allcloudsnz** [abhn/Wall-E#3]
It appears that after each post, i have to manually delete the index.html and archive.html page from _sites folder, and re-run sudo jekyll serve --host=192.168.1.xx .

I have tried sudo jekyll serve --host=192.168.1.xx --incremental but that doesn't seem to resolve the issue, until i delete the files.

Is it me, or am i doing something wrong!

**Comment by abhn** [comment]
1. You don't need to sudo jekyll, for testing, ```jekyll server``` should work on port 3000 
2. You should never need to touch anything in the _site folder
3. Is your _config.yml alright? I guess that might be one issue

I have never faced this problem, so can't be sure. Sorry.
