### ISSUE TITLE
Lunr Search

### ISSUE THREAD

**Issue by allcloudsnz** [abhn/Wall-E#4]
hopefully you can implement this.

Right now your search in wall-e theme for jekyll is utilising google search. it doesn't appear to run ok,

any chance if you can create a search page based on the lunr searh, as per below

https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/#introduction

Perhaps the searcg page will be same as archiev page, lsiting all archives and results change upon search results.

**Comment by allcloudsnz** [comment]
any one?

**Comment by abhn** [comment]
Sorry, have been busy with work. If anyone wants to take it up, please feel free.

**Comment by Etone** [comment]
Hello there, 
I have a small branch where I got this to work, unfortunately not with the currently used search bar but with a new search page. And I have removed the search bar (two of them would be slightly confusing). 
If there is still interest I could push this branch for someone with more knowledge to maybe get it to work with the current search bar implementation.

**Comment by abhn** [comment]
@Etone hey your search works great! I'll try integrating your code into the previous search input. 

Thanks :)

**Comment by Etone** [comment]
I hope you can get this to work, as I do not have the js knowledge for this. Thanks a lot for your work on this theme

**Comment by allcloudsnz** [comment]
how about removing the searchbar. and implementing the search page.

search page can perhaps by default list the top 50 posts, just like the
arcieve page.

but it will also have a search function on the top of this page. as you
type/search, the lists are of posts shows accordingly.

cheers

**Comment by Etone** [comment]
@allcloudsnz If you look at my current ([master branch](https://github.com/Etone/etone.github.io))  There is an implemented Version of this solution. With Commit 3dc454935a756345b0a0da385d0500d36902948c I implemented this. But as i said, it does not work with the currently integrated searchbar, but with its own page. And it is not the most beautiful solution, as I wanted to introduce some sort of live search which shows found blogpostst while typing something in the search box (which i could not get to work). I hope this can help you with your problem, at least temporarily until @abhn implements a proper way of doing this search

**Comment by allcloudsnz** [comment]
thanks, have managed to get it going and loving it.

cheers
