### ISSUE TITLE
Increase fonts

### ISSUE THREAD

**Issue by allcloudsnz** [abhn/Wall-E#5]
i am wanting to increase the fonts of the entire site. how do i archive this.

Say for example: browse to https://wall-e-jekyll.github.io/ in any browser, zoom to 110%

thats the size i prefer my entire site. please advise.

**Comment by abhn** [comment]
Hey hi, there's no straight forward way to do it. Increasing the zoom level actually increases many things apart from the font-size.

One (very hacky) solution is to do body { font-size: 110% }, which will increase sizes of all fonts which have not been explicitly marked, but for individual elements (with explicit font sizes like semantic stuff) you'll need to do it on a per element basis.

Hope that helps.
