### ISSUE TITLE
Modifiyng URL's Posts

### ISSUE THREAD

**Issue by neoranger** [abhn/Wall-E#7]
Hi! Im using your theme in your blog but in the settings of the theme i have to use .html in my url's blog. So, when some people try to use the Disqus links it take the urls without the .html so they get 404 error. How i can change that? Thanks!

![image](https://user-images.githubusercontent.com/5490758/42530246-10fd0fd6-8457-11e8-9fa5-04aeae091ea5.png)

![image](https://user-images.githubusercontent.com/5490758/42530276-27737d72-8457-11e8-9553-bb88f4265337.png)

**Comment by abhn** [comment]
Hey @neoranger , thanks for using this theme.

You can try omitting the `.html` part in the parmalink setting in `_config.yml` (https://github.com/abhn/Wall-E/blob/master/_config.yml#L10)

Change `permalink: /:year/:month/:title.html` to `permalink: /:year/:month/:title`

Hope that was your issue. You'll need to restart jekyll server after making the change. Cheers.

**Comment by neoranger** [comment]
@abhn Thanks for the answer. Doing that doesn't work the html pages, such as, About, Archive, etc. Can i do something else?
