### ISSUE TITLE
How set-up google analytics

### ISSUE THREAD

**Issue by neoranger** [abhn/Wall-E#8]
Hi! How could i set-up Google analitycs correctly?? I put the analytics ID in my _config.yml but doesn't work.

**Comment by abhn** [comment]
Thank you for dropping by.

No, it won't work in `_config.yml` as that file's just for configuration variables and other settings. 

Please add the Google Analytics code in this file (https://github.com/abhn/Wall-E/blob/master/_includes/head.html) inside the `<head></head>` tag. 

Google recommends putting the script right after the opening `<head>` tag.

Hope that helps, thanks.

**Comment by neoranger** [comment]
Thanks!!!
